version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
      # The secondary container is an instance of the second listed image which is run in a common network where ports exposed on the primary container are available on localhost.
    steps:
      - checkout
      - run: npm install
      - run: npm start
